default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: dba
  password: admin

development:
  <<: *default
  database: cuido_development

test:
  <<: *default
  database: cuido_test
